/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AlignmentConfig } from './alignment-config';
// May contain unused imports in some cases
// @ts-ignore
import type { AudioEventsConfig } from './audio-events-config';
// May contain unused imports in some cases
// @ts-ignore
import type { DataFetchConfig } from './data-fetch-config';
// May contain unused imports in some cases
// @ts-ignore
import type { JobType } from './job-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LanguageIdentificationConfig } from './language-identification-config';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationConfig } from './notification-config';
// May contain unused imports in some cases
// @ts-ignore
import type { OutputConfig } from './output-config';
// May contain unused imports in some cases
// @ts-ignore
import type { SummarizationConfig } from './summarization-config';
// May contain unused imports in some cases
// @ts-ignore
import type { TopicDetectionConfig } from './topic-detection-config';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackingData } from './tracking-data';
// May contain unused imports in some cases
// @ts-ignore
import type { TranscriptionConfig } from './transcription-config';
// May contain unused imports in some cases
// @ts-ignore
import type { TranslationConfig } from './translation-config';

/**
 * JSON object that contains various groups of job configuration parameters. Based on the value of `type`, a type-specific object such as `transcription_config` is required to be present to specify all configuration settings or parameters needed to process the job inputs as expected.  If the results of the job are to be forwarded on completion, `notification_config` can be provided with a list of callbacks to be made; no assumptions should be made about the order in which they will occur.  Customer specific job details or metadata can be supplied in `tracking`, and this information will be available where possible in the job results and in callbacks.
 * @export
 * @interface JobConfig
 */
export interface JobConfig {
  /**
   *
   * @type {JobType}
   * @memberof JobConfig
   */
  type: JobType;
  /**
   *
   * @type {DataFetchConfig}
   * @memberof JobConfig
   */
  fetch_data?: DataFetchConfig;
  /**
   *
   * @type {DataFetchConfig}
   * @memberof JobConfig
   */
  fetch_text?: DataFetchConfig;
  /**
   *
   * @type {AlignmentConfig}
   * @memberof JobConfig
   */
  alignment_config?: AlignmentConfig;
  /**
   *
   * @type {TranscriptionConfig}
   * @memberof JobConfig
   */
  transcription_config?: TranscriptionConfig;
  /**
   *
   * @type {Array<NotificationConfig>}
   * @memberof JobConfig
   */
  notification_config?: Array<NotificationConfig>;
  /**
   *
   * @type {TrackingData}
   * @memberof JobConfig
   */
  tracking?: TrackingData;
  /**
   *
   * @type {OutputConfig}
   * @memberof JobConfig
   */
  output_config?: OutputConfig;
  /**
   *
   * @type {TranslationConfig}
   * @memberof JobConfig
   */
  translation_config?: TranslationConfig;
  /**
   *
   * @type {LanguageIdentificationConfig}
   * @memberof JobConfig
   */
  language_identification_config?: LanguageIdentificationConfig;
  /**
   *
   * @type {SummarizationConfig}
   * @memberof JobConfig
   */
  summarization_config?: SummarizationConfig;
  /**
   *
   * @type {object}
   * @memberof JobConfig
   */
  sentiment_analysis_config?: object;
  /**
   *
   * @type {TopicDetectionConfig}
   * @memberof JobConfig
   */
  topic_detection_config?: TopicDetectionConfig;
  /**
   *
   * @type {object}
   * @memberof JobConfig
   */
  auto_chapters_config?: object;
  /**
   *
   * @type {AudioEventsConfig}
   * @memberof JobConfig
   */
  audio_events_config?: AudioEventsConfig;
}
