import type { Metadata } from 'next';
import './globals.css';
import '@picocss/pico';
import { FlowProvider } from '@speechmatics/flow-client-react';

export const metadata: Metadata = {
  title: 'Speechmatics Flow example',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FlowProvider appId="nextjs-example">
        <body>{children}</body>
      </FlowProvider>
    </html>
  );
}
