/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AudioEventEnded
 */
export interface AudioEventEnded {
  /**
   *
   * @type {string}
   * @memberof AudioEventEnded
   */
  type?: string;
  /**
   *
   * @type {number}
   * @memberof AudioEventEnded
   */
  end_time?: number;
}
