/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TranslatedSentence
 */
export interface TranslatedSentence {
  /**
   *
   * @type {string}
   * @memberof TranslatedSentence
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof TranslatedSentence
   */
  start_time: number;
  /**
   *
   * @type {number}
   * @memberof TranslatedSentence
   */
  end_time: number;
  /**
   *
   * @type {string}
   * @memberof TranslatedSentence
   */
  speaker?: string;
}
