/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AudioFilteringConfig } from './audio-filtering-config';
// May contain unused imports in some cases
// @ts-ignore
import type { DiarizationConfig } from './diarization-config';
// May contain unused imports in some cases
// @ts-ignore
import type { MaxDelayModeConfig } from './max-delay-mode-config';
// May contain unused imports in some cases
// @ts-ignore
import type { OperatingPoint } from './operating-point';
// May contain unused imports in some cases
// @ts-ignore
import type { PunctuationOverrides } from './punctuation-overrides';
// May contain unused imports in some cases
// @ts-ignore
import type { SpeakerDiarizationConfig } from './speaker-diarization-config';
// May contain unused imports in some cases
// @ts-ignore
import type { TranscriptFilteringConfig } from './transcript-filtering-config';
// May contain unused imports in some cases
// @ts-ignore
import type { VocabWord } from './vocab-word';

/**
 *
 * @export
 * @interface TranscriptionConfig
 */
export interface TranscriptionConfig {
  /**
   *
   * @type {string}
   * @memberof TranscriptionConfig
   */
  language: string;
  /**
   * Request a specialized model based on \'language\' but optimized for a particular field, e.g. \"finance\" or \"medical\".
   * @type {string}
   * @memberof TranscriptionConfig
   */
  domain?: string;
  /**
   *
   * @type {string}
   * @memberof TranscriptionConfig
   */
  output_locale?: string;
  /**
   *
   * @type {Array<VocabWord>}
   * @memberof TranscriptionConfig
   */
  additional_vocab?: Array<VocabWord>;
  /**
   *
   * @type {DiarizationConfig}
   * @memberof TranscriptionConfig
   */
  diarization?: DiarizationConfig;
  /**
   *
   * @type {number}
   * @memberof TranscriptionConfig
   */
  max_delay?: number;
  /**
   *
   * @type {MaxDelayModeConfig}
   * @memberof TranscriptionConfig
   */
  max_delay_mode?: MaxDelayModeConfig;
  /**
   *
   * @type {SpeakerDiarizationConfig}
   * @memberof TranscriptionConfig
   */
  speaker_diarization_config?: SpeakerDiarizationConfig;
  /**
   *
   * @type {AudioFilteringConfig}
   * @memberof TranscriptionConfig
   */
  audio_filtering_config?: AudioFilteringConfig;
  /**
   *
   * @type {TranscriptFilteringConfig}
   * @memberof TranscriptionConfig
   */
  transcript_filtering_config?: TranscriptFilteringConfig;
  /**
   *
   * @type {boolean}
   * @memberof TranscriptionConfig
   */
  enable_partials?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TranscriptionConfig
   */
  enable_entities?: boolean;
  /**
   *
   * @type {OperatingPoint}
   * @memberof TranscriptionConfig
   */
  operating_point?: OperatingPoint;
  /**
   *
   * @type {PunctuationOverrides}
   * @memberof TranscriptionConfig
   */
  punctuation_overrides?: PunctuationOverrides;
}
