/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TranslationConfig
 */
export interface TranslationConfig {
  /**
   *
   * @type {Array<string>}
   * @memberof TranslationConfig
   */
  target_languages: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof TranslationConfig
   */
  enable_partials?: boolean;
}
