/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AudioEventItem
 */
export interface AudioEventItem {
  /**
   * Input channel this event occurred on
   * @type {string}
   * @memberof AudioEventItem
   */
  channel?: string;
  /**
   * Prediction confidence associated with this event
   * @type {number}
   * @memberof AudioEventItem
   */
  confidence?: number;
  /**
   * Time (in seconds) at which the audio event ends
   * @type {number}
   * @memberof AudioEventItem
   */
  end_time?: number;
  /**
   * Time (in seconds) at which the audio event starts
   * @type {number}
   * @memberof AudioEventItem
   */
  start_time?: number;
  /**
   * Kind of audio event. E.g. music
   * @type {string}
   * @memberof AudioEventItem
   */
  type?: string;
}
