/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Summary statistics for this audio event type
 * @export
 * @interface AudioEventSummaryItem
 */
export interface AudioEventSummaryItem {
  /**
   * Number of events of this type
   * @type {number}
   * @memberof AudioEventSummaryItem
   */
  count?: number;
  /**
   * Total duration (in seconds) of all audio events of this type
   * @type {number}
   * @memberof AudioEventSummaryItem
   */
  total_duration?: number;
}
