/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Configuration for limiting the transcription of quiet audio.
 * @export
 * @interface BatchTranscriptionConfigAudioFilteringConfig
 */
export interface BatchTranscriptionConfigAudioFilteringConfig {
  /**
   * Controls the lower limit of audio volume at which speech and audio events will be transcribed. If the volume limit is very low, then most sound will be passed to the speech recognition engine. Higher numbers will cut out increasing amounts of sound.
   * @type {number}
   * @memberof BatchTranscriptionConfigAudioFilteringConfig
   */
  volume_threshold?: number;
}
