/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BatchTranslationConfig
 */
export interface BatchTranslationConfig {
  /**
   * Array of ISO language codes that you would like your audio to be translated into.
   * @type {Array<string>}
   * @memberof BatchTranslationConfig
   */
  target_languages: Array<string>;
}
