/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BatchRecognitionDisplay } from './batch-recognition-display';

/**
 * List of possible job output item values, ordered by likelihood.
 * @export
 * @interface BatchRecognitionAlternative
 */
export interface BatchRecognitionAlternative {
  /**
   *
   * @type {number}
   * @memberof BatchRecognitionAlternative
   */
  confidence: number;
  /**
   *
   * @type {string}
   * @memberof BatchRecognitionAlternative
   */
  content: string;
  /**
   *
   * @type {BatchRecognitionDisplay}
   * @memberof BatchRecognitionAlternative
   */
  display?: BatchRecognitionDisplay;
  /**
   *
   * @type {string}
   * @memberof BatchRecognitionAlternative
   */
  language: string;
  /**
   *
   * @type {string}
   * @memberof BatchRecognitionAlternative
   */
  speaker?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof BatchRecognitionAlternative
   */
  tags?: Array<string>;
}
