/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AlignmentConfig } from './alignment-config';
// May contain unused imports in some cases
// @ts-ignore
import { BatchTranscriptionConfig } from './batch-transcription-config';
// May contain unused imports in some cases
// @ts-ignore
import { JobType } from './job-type';
// May contain unused imports in some cases
// @ts-ignore
import { OutputConfig } from './output-config';

/**
 * Summary information about the output from an ASR job, comprising the job type and configuration parameters used when generating the output
 * @export
 * @interface BatchRecognitionMetadata
 */
export interface BatchRecognitionMetadata {
  /**
   *
   * @type {AlignmentConfig}
   * @memberof BatchRecognitionMetadata
   */
  alignment_config?: AlignmentConfig;
  /**
   * The UTC date time the transcription output was created.
   * @type {string}
   * @memberof BatchRecognitionMetadata
   */
  created_at: string;
  /**
   *
   * @type {OutputConfig}
   * @memberof BatchRecognitionMetadata
   */
  output_config?: OutputConfig;
  /**
   *
   * @type {BatchTranscriptionConfig}
   * @memberof BatchRecognitionMetadata
   */
  transcription_config?: BatchTranscriptionConfig;
  /**
   *
   * @type {JobType}
   * @memberof BatchRecognitionMetadata
   */
  type: JobType;
}
