/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BatchTranscriptionConfigAdditionalVocabInner } from './batch-transcription-config-additional-vocab-inner';
// May contain unused imports in some cases
// @ts-ignore
import { BatchTranscriptionConfigAudioFilteringConfig } from './batch-transcription-config-audio-filtering-config';
// May contain unused imports in some cases
// @ts-ignore
import { BatchTranscriptionConfigPunctuationOverrides } from './batch-transcription-config-punctuation-overrides';
// May contain unused imports in some cases
// @ts-ignore
import { BatchTranscriptionConfigSpeakerDiarizationConfig } from './batch-transcription-config-speaker-diarization-config';
// May contain unused imports in some cases
// @ts-ignore
import { OperatingPoint } from './operating-point';

/**
 *
 * @export
 * @interface BatchTranscriptionConfig
 */
export interface BatchTranscriptionConfig {
  /**
   * List of custom words or phrases that should be recognized. Alternative pronunciations can be specified to aid recognition.
   * @type {Array<BatchTranscriptionConfigAdditionalVocabInner>}
   * @memberof BatchTranscriptionConfig
   */
  additional_vocab?: Array<BatchTranscriptionConfigAdditionalVocabInner>;
  /**
   *
   * @type {BatchTranscriptionConfigAudioFilteringConfig}
   * @memberof BatchTranscriptionConfig
   */
  audio_filtering_config?: BatchTranscriptionConfigAudioFilteringConfig;
  /**
   * Transcript labels to use when using collating separate input channels.
   * @type {Array<string>}
   * @memberof BatchTranscriptionConfig
   */
  channel_diarization_labels?: Array<string>;
  /**
   * Specify whether speaker or channel labels are added to the transcript. The default is `none`.   - **none**: no speaker or channel labels are added.   - **speaker**: speaker attribution is performed based on acoustic matching;              all input channels are mixed into a single stream for processing.   - **channel**: multiple input channels are processed individually and collated             into a single transcript.   - **speaker_change**: the output indicates when the speaker in the audio changes.                     No speaker attribution is performed. This is a faster method                     than speaker. The reported speaker changes may not agree with speaker.   - **channel_and_speaker_change**: both channel and speaker_change are switched on.                                 The speaker change is indicated if more than one speaker                                 are recorded in one channel.
   * @type {string}
   * @memberof BatchTranscriptionConfig
   */
  diarization?: BatchTranscriptionConfigDiarizationEnum;
  /**
   * Request a specialized model based on \'language\' but optimized for a particular field, e.g. \"finance\" or \"medical\".
   * @type {string}
   * @memberof BatchTranscriptionConfig
   */
  domain?: string;
  /**
   * Include additional \'entity\' objects in the transcription results (e.g. dates, numbers) and their original spoken form. These entities are interleaved with other types of results. The concatenation of these words is represented as a single entity with the concatenated written form present in the \'content\' field. The entities contain a \'spoken_form\' field, which can be used in place of the corresponding \'word\' type results, in case a spoken form is preferred to a written form. They also contain a \'written_form\', which can be used instead of the entity, if you want a breakdown of the words without spaces. They can still contain non-breaking spaces and other special whitespace characters, as they are considered part of the word for the formatting output. In case of a written_form, the individual word times are estimated and might not be accurate if the order of the words in the written form does not correspond to the order they were actually spoken (such as \'one hundred million dollars\' and \'$100 million\').
   * @type {boolean}
   * @memberof BatchTranscriptionConfig
   */
  enable_entities?: boolean;
  /**
   * Language model to process the audio input, normally specified as an ISO language code
   * @type {string}
   * @memberof BatchTranscriptionConfig
   */
  language: string;
  /**
   * Whether or not to enable flexible endpointing and allow the entity to continue to be spoken.
   * @type {string}
   * @memberof BatchTranscriptionConfig
   */
  max_delay_mode?: BatchTranscriptionConfigMaxDelayModeEnum;
  /**
   *
   * @type {OperatingPoint}
   * @memberof BatchTranscriptionConfig
   */
  operating_point?: OperatingPoint;
  /**
   * Language locale to be used when generating the transcription output, normally specified as an ISO language code
   * @type {string}
   * @memberof BatchTranscriptionConfig
   */
  output_locale?: string;
  /**
   *
   * @type {BatchTranscriptionConfigPunctuationOverrides}
   * @memberof BatchTranscriptionConfig
   */
  punctuation_overrides?: BatchTranscriptionConfigPunctuationOverrides;
  /**
   * Ranges between zero and one. Controls how responsive the system is for potential speaker changes. High value indicates high sensitivity. Defaults to 0.4.
   * @type {number}
   * @memberof BatchTranscriptionConfig
   */
  speaker_change_sensitivity?: number;
  /**
   *
   * @type {BatchTranscriptionConfigSpeakerDiarizationConfig}
   * @memberof BatchTranscriptionConfig
   */
  speaker_diarization_config?: BatchTranscriptionConfigSpeakerDiarizationConfig;
}

export const BatchTranscriptionConfigDiarizationEnum = {
  None: 'none',
  Speaker: 'speaker',
  Channel: 'channel',
  SpeakerChange: 'speaker_change',
  ChannelAndSpeakerChange: 'channel_and_speaker_change',
} as const;

export type BatchTranscriptionConfigDiarizationEnum =
  typeof BatchTranscriptionConfigDiarizationEnum[keyof typeof BatchTranscriptionConfigDiarizationEnum];
export const BatchTranscriptionConfigMaxDelayModeEnum = {
  Fixed: 'fixed',
  Flexible: 'flexible',
} as const;

export type BatchTranscriptionConfigMaxDelayModeEnum =
  typeof BatchTranscriptionConfigMaxDelayModeEnum[keyof typeof BatchTranscriptionConfigMaxDelayModeEnum];
