/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Chapter
 */
export interface Chapter {
  /**
   *
   * @type {number}
   * @memberof Chapter
   */
  end_time?: number;
  /**
   *
   * @type {number}
   * @memberof Chapter
   */
  start_time?: number;
  /**
   *
   * @type {string}
   * @memberof Chapter
   */
  summary?: string;
  /**
   *
   * @type {string}
   * @memberof Chapter
   */
  title?: string;
}
