/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateJobResponse
 */
export interface CreateJobResponse {
  /**
   * The unique ID assigned to the job. Keep a record of this for later retrieval of your completed job.
   * @type {string}
   * @memberof CreateJobResponse
   */
  id: string;
}
