/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AlignmentConfig } from './alignment-config';
// May contain unused imports in some cases
// @ts-ignore
import { BatchAudioEventsConfig } from './batch-audio-events-config';
// May contain unused imports in some cases
// @ts-ignore
import { BatchTranscriptionConfig } from './batch-transcription-config';
// May contain unused imports in some cases
// @ts-ignore
import { BatchTranslationConfig } from './batch-translation-config';
// May contain unused imports in some cases
// @ts-ignore
import { DataFetchConfig } from './data-fetch-config';
// May contain unused imports in some cases
// @ts-ignore
import { JobType } from './job-type';
// May contain unused imports in some cases
// @ts-ignore
import { LanguageIdentificationConfig } from './language-identification-config';
// May contain unused imports in some cases
// @ts-ignore
import { NotificationConfig } from './notification-config';
// May contain unused imports in some cases
// @ts-ignore
import { OutputConfig } from './output-config';
// May contain unused imports in some cases
// @ts-ignore
import { SummarizationConfig } from './summarization-config';
// May contain unused imports in some cases
// @ts-ignore
import { TopicDetectionConfig } from './topic-detection-config';
// May contain unused imports in some cases
// @ts-ignore
import { TrackingData } from './tracking-data';

/**
 * JSON object that contains various groups of job configuration parameters. Based on the value of `type`, a type-specific object such as `transcription_config` is required to be present to specify all configuration settings or parameters needed to process the job inputs as expected.  If the results of the job are to be forwarded on completion, `notification_config` can be provided with a list of callbacks to be made; no assumptions should be made about the order in which they will occur.  Customer specific job details or metadata can be supplied in `tracking`, and this information will be available where possible in the job results and in callbacks.
 * @export
 * @interface JobConfig
 */
export interface JobConfig {
  /**
   *
   * @type {AlignmentConfig}
   * @memberof JobConfig
   */
  alignment_config?: AlignmentConfig;
  /**
   *
   * @type {BatchAudioEventsConfig}
   * @memberof JobConfig
   */
  audio_events_config?: BatchAudioEventsConfig;
  /**
   *
   * @type {object}
   * @memberof JobConfig
   */
  auto_chapters_config?: object;
  /**
   *
   * @type {DataFetchConfig}
   * @memberof JobConfig
   */
  fetch_data?: DataFetchConfig;
  /**
   *
   * @type {DataFetchConfig}
   * @memberof JobConfig
   */
  fetch_text?: DataFetchConfig;
  /**
   *
   * @type {LanguageIdentificationConfig}
   * @memberof JobConfig
   */
  language_identification_config?: LanguageIdentificationConfig;
  /**
   *
   * @type {Array<NotificationConfig>}
   * @memberof JobConfig
   */
  notification_config?: Array<NotificationConfig>;
  /**
   *
   * @type {OutputConfig}
   * @memberof JobConfig
   */
  output_config?: OutputConfig;
  /**
   *
   * @type {object}
   * @memberof JobConfig
   */
  sentiment_analysis_config?: object;
  /**
   *
   * @type {SummarizationConfig}
   * @memberof JobConfig
   */
  summarization_config?: SummarizationConfig;
  /**
   *
   * @type {TopicDetectionConfig}
   * @memberof JobConfig
   */
  topic_detection_config?: TopicDetectionConfig;
  /**
   *
   * @type {TrackingData}
   * @memberof JobConfig
   */
  tracking?: TrackingData;
  /**
   *
   * @type {BatchTranscriptionConfig}
   * @memberof JobConfig
   */
  transcription_config?: BatchTranscriptionConfig;
  /**
   *
   * @type {BatchTranslationConfig}
   * @memberof JobConfig
   */
  translation_config?: BatchTranslationConfig;
  /**
   *
   * @type {JobType}
   * @memberof JobConfig
   */
  type: JobType;
}
