/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Properties of the language pack.
 * @export
 * @interface LanguagePackInfo
 */
export interface LanguagePackInfo {
  /**
   * Whether or not language model adaptation has been applied to the language pack.
   * @type {boolean}
   * @memberof LanguagePackInfo
   */
  adapted?: boolean;
  /**
   * Whether or not ITN (inverse text normalization) is available for the language pack.
   * @type {boolean}
   * @memberof LanguagePackInfo
   */
  itn?: boolean;
  /**
   * Full descriptive name of the language, e.g. \'Japanese\'.
   * @type {string}
   * @memberof LanguagePackInfo
   */
  language_description?: string;
  /**
   * The character to use to separate words.
   * @type {string}
   * @memberof LanguagePackInfo
   */
  word_delimiter: string;
  /**
   * The direction that words in the language should be written and read in.
   * @type {string}
   * @memberof LanguagePackInfo
   */
  writing_direction?: LanguagePackInfoWritingDirectionEnum;
}

export const LanguagePackInfoWritingDirectionEnum = {
  LeftToRight: 'left-to-right',
  RightToLeft: 'right-to-left',
} as const;

export type LanguagePackInfoWritingDirectionEnum =
  typeof LanguagePackInfoWritingDirectionEnum[keyof typeof LanguagePackInfoWritingDirectionEnum];
