/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RealtimeRecognitionDisplay } from './realtime-recognition-display';

/**
 *
 * @export
 * @interface RealtimeRecognitionAlternative
 */
export interface RealtimeRecognitionAlternative {
  /**
   *
   * @type {number}
   * @memberof RealtimeRecognitionAlternative
   */
  confidence: number;
  /**
   *
   * @type {string}
   * @memberof RealtimeRecognitionAlternative
   */
  content: string;
  /**
   *
   * @type {RealtimeRecognitionDisplay}
   * @memberof RealtimeRecognitionAlternative
   */
  display?: RealtimeRecognitionDisplay;
  /**
   *
   * @type {string}
   * @memberof RealtimeRecognitionAlternative
   */
  language?: string;
  /**
   *
   * @type {string}
   * @memberof RealtimeRecognitionAlternative
   */
  speaker?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof RealtimeRecognitionAlternative
   */
  tags?: Array<string>;
}
