/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SentimentAnalysisError
 */
export interface SentimentAnalysisError {
  /**
   * Human readable error message
   * @type {string}
   * @memberof SentimentAnalysisError
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof SentimentAnalysisError
   */
  type?: SentimentAnalysisErrorTypeEnum;
}

export const SentimentAnalysisErrorTypeEnum = {
  SentimentAnalysisFailed: 'sentiment_analysis_failed',
  UnsupportedLanguage: 'unsupported_language',
} as const;

export type SentimentAnalysisErrorTypeEnum =
  typeof SentimentAnalysisErrorTypeEnum[keyof typeof SentimentAnalysisErrorTypeEnum];
