/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Holds the count of sentiment information grouped by positive, neutral and negative.
 * @export
 * @interface SentimentSummaryDetail
 */
export interface SentimentSummaryDetail {
  /**
   *
   * @type {number}
   * @memberof SentimentSummaryDetail
   */
  negative_count?: number;
  /**
   *
   * @type {number}
   * @memberof SentimentSummaryDetail
   */
  neutral_count?: number;
  /**
   *
   * @type {number}
   * @memberof SentimentSummaryDetail
   */
  positive_count?: number;
}
