/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a segment of text and its associated sentiment.
 * @export
 * @interface SentimentSegment
 */
export interface SentimentSegment {
  /**
   *
   * @type {string}
   * @memberof SentimentSegment
   */
  channel?: string;
  /**
   *
   * @type {number}
   * @memberof SentimentSegment
   */
  confidence?: number;
  /**
   *
   * @type {number}
   * @memberof SentimentSegment
   */
  end_time?: number;
  /**
   *
   * @type {string}
   * @memberof SentimentSegment
   */
  sentiment?: string;
  /**
   *
   * @type {string}
   * @memberof SentimentSegment
   */
  speaker?: string;
  /**
   *
   * @type {number}
   * @memberof SentimentSegment
   */
  start_time?: number;
  /**
   *
   * @type {string}
   * @memberof SentimentSegment
   */
  text?: string;
}
