/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SentimentChannelSummary } from './sentiment-channel-summary';
// May contain unused imports in some cases
// @ts-ignore
import { SentimentSpeakerSummary } from './sentiment-speaker-summary';
// May contain unused imports in some cases
// @ts-ignore
import { SentimentSummaryDetail } from './sentiment-summary-detail';

/**
 * Holds overall sentiment information, as well as detailed per-speaker and per-channel sentiment data.
 * @export
 * @interface SentimentSummary
 */
export interface SentimentSummary {
  /**
   * An array of objects that represent sentiment data for a specific channel.
   * @type {Array<SentimentChannelSummary>}
   * @memberof SentimentSummary
   */
  channels?: Array<SentimentChannelSummary>;
  /**
   *
   * @type {SentimentSummaryDetail}
   * @memberof SentimentSummary
   */
  overall?: SentimentSummaryDetail;
  /**
   * An array of objects that represent sentiment data for a specific speaker.
   * @type {Array<SentimentSpeakerSummary>}
   * @memberof SentimentSummary
   */
  speakers?: Array<SentimentSpeakerSummary>;
}
