/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Holds sentiment information for a specific speaker.
 * @export
 * @interface SentimentSpeakerSummary
 */
export interface SentimentSpeakerSummary {
  /**
   *
   * @type {number}
   * @memberof SentimentSpeakerSummary
   */
  negative_count?: number;
  /**
   *
   * @type {number}
   * @memberof SentimentSpeakerSummary
   */
  neutral_count?: number;
  /**
   *
   * @type {number}
   * @memberof SentimentSpeakerSummary
   */
  positive_count?: number;
  /**
   *
   * @type {string}
   * @memberof SentimentSpeakerSummary
   */
  speaker?: string;
}
