/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TopicDetectionError
 */
export interface TopicDetectionError {
  /**
   * Human readable error message
   * @type {string}
   * @memberof TopicDetectionError
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof TopicDetectionError
   */
  type?: TopicDetectionErrorTypeEnum;
}

export const TopicDetectionErrorTypeEnum = {
  TopicDetectionFailed: 'topic_detection_failed',
  UnsupportedListOfTopics: 'unsupported_list_of_topics',
  UnsupportedLanguage: 'unsupported_language',
} as const;

export type TopicDetectionErrorTypeEnum =
  typeof TopicDetectionErrorTypeEnum[keyof typeof TopicDetectionErrorTypeEnum];
