/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TopicDetectionSegmentTopic } from './topic-detection-segment-topic';

/**
 * Represents a segment of text and its associated topic information.
 * @export
 * @interface TopicDetectionSegment
 */
export interface TopicDetectionSegment {
  /**
   *
   * @type {number}
   * @memberof TopicDetectionSegment
   */
  end_time?: number;
  /**
   *
   * @type {number}
   * @memberof TopicDetectionSegment
   */
  start_time?: number;
  /**
   *
   * @type {string}
   * @memberof TopicDetectionSegment
   */
  text?: string;
  /**
   *
   * @type {Array<TopicDetectionSegmentTopic>}
   * @memberof TopicDetectionSegment
   */
  topics?: Array<TopicDetectionSegmentTopic>;
}
