/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Holds overall information on the topics detected.
 * @export
 * @interface TopicDetectionSummary
 */
export interface TopicDetectionSummary {
  /**
   * Holds the count of topics detected.
   * @type {{ [key: string]: number; }}
   * @memberof TopicDetectionSummary
   */
  overall?: { [key: string]: number };
}
