/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TrackingData
 */
export interface TrackingData {
  /**
   * Customer-defined JSON structure.
   * @type {object}
   * @memberof TrackingData
   */
  details?: object;
  /**
   * External system reference.
   * @type {string}
   * @memberof TrackingData
   */
  reference?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof TrackingData
   */
  tags?: Array<string>;
  /**
   * The title of the job.
   * @type {string}
   * @memberof TrackingData
   */
  title?: string;
}
