/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { JobMode } from './job-mode';
// May contain unused imports in some cases
// @ts-ignore
import { JobType } from './job-type';
// May contain unused imports in some cases
// @ts-ignore
import { OperatingPoint } from './operating-point';

/**
 *
 * @export
 * @interface UsageDetails
 */
export interface UsageDetails {
  /**
   * Total number of billable jobs in this cycle
   * @type {number}
   * @memberof UsageDetails
   */
  count: number;
  /**
   * Total duration of billable jobs (in hours) this cycle
   * @type {number}
   * @memberof UsageDetails
   */
  duration_hrs: number;
  /**
   *
   * @type {string}
   * @memberof UsageDetails
   */
  language?: string;
  /**
   *
   * @type {JobMode}
   * @memberof UsageDetails
   */
  mode: JobMode;
  /**
   *
   * @type {OperatingPoint}
   * @memberof UsageDetails
   */
  operating_point?: OperatingPoint;
  /**
   *
   * @type {JobType}
   * @memberof UsageDetails
   */
  type: JobType;
}
