/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Summary statistics for this audio event type
 * @export
 * @interface AudioEventSummaryItem
 */
export interface AudioEventSummaryItem {
  /**
   * Total duration (in seconds) of all audio events of this type
   * @type {number}
   * @memberof AudioEventSummaryItem
   */
  total_duration?: number;
  /**
   * Number of events of this type
   * @type {number}
   * @memberof AudioEventSummaryItem
   */
  count?: number;
}
