/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AudioEventItem
 */
export interface AudioEventItem {
  /**
   * Kind of audio event. E.g. music
   * @type {string}
   * @memberof AudioEventItem
   */
  type?: string;
  /**
   * Time (in seconds) at which the audio event starts
   * @type {number}
   * @memberof AudioEventItem
   */
  start_time?: number;
  /**
   * Time (in seconds) at which the audio event ends
   * @type {number}
   * @memberof AudioEventItem
   */
  end_time?: number;
  /**
   * Prediction confidence associated with this event
   * @type {number}
   * @memberof AudioEventItem
   */
  confidence?: number;
  /**
   * Input channel this event occurred on
   * @type {string}
   * @memberof AudioEventItem
   */
  channel?: string;
}
