/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TrackingData } from './tracking-data';

/**
 * Summary information about an ASR job, to support identification and tracking.
 * @export
 * @interface JobInfo
 */
export interface JobInfo {
  /**
   * The UTC date time the job was created.
   * @type {string}
   * @memberof JobInfo
   */
  created_at: string;
  /**
   * Name of data file submitted for job.
   * @type {string}
   * @memberof JobInfo
   */
  data_name: string;
  /**
   * The data file audio duration (in seconds).
   * @type {number}
   * @memberof JobInfo
   */
  duration: number;
  /**
   * The unique id assigned to the job.
   * @type {string}
   * @memberof JobInfo
   */
  id: string;
  /**
   * Name of the text file submitted to be aligned to audio.
   * @type {string}
   * @memberof JobInfo
   */
  text_name?: string;
  /**
   *
   * @type {TrackingData}
   * @memberof JobInfo
   */
  tracking?: TrackingData;
}
