/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AlignmentConfig } from './alignment-config';
// May contain unused imports in some cases
// @ts-ignore
import type { AutoChaptersResultError } from './auto-chapters-result-error';
// May contain unused imports in some cases
// @ts-ignore
import type { JobType } from './job-type';
// May contain unused imports in some cases
// @ts-ignore
import type { LanguageIdentificationResult } from './language-identification-result';
// May contain unused imports in some cases
// @ts-ignore
import type { LanguagePackInfo } from './language-pack-info';
// May contain unused imports in some cases
// @ts-ignore
import type { OutputConfig } from './output-config';
// May contain unused imports in some cases
// @ts-ignore
import type { SentimentAnalysisError } from './sentiment-analysis-error';
// May contain unused imports in some cases
// @ts-ignore
import type { SummarizationError } from './summarization-error';
// May contain unused imports in some cases
// @ts-ignore
import type { TopicDetectionError } from './topic-detection-error';
// May contain unused imports in some cases
// @ts-ignore
import type { TranscriptionConfig } from './transcription-config';
// May contain unused imports in some cases
// @ts-ignore
import type { TranslationError } from './translation-error';

/**
 * Summary information about the output from an ASR job, comprising the job type and configuration parameters used when generating the output.
 * @export
 * @interface RecognitionMetadata
 */
export interface RecognitionMetadata {
  /**
   * The UTC date time the transcription output was created.
   * @type {string}
   * @memberof RecognitionMetadata
   */
  created_at: string;
  /**
   *
   * @type {JobType}
   * @memberof RecognitionMetadata
   */
  type: JobType;
  /**
   *
   * @type {TranscriptionConfig}
   * @memberof RecognitionMetadata
   */
  transcription_config?: TranscriptionConfig;
  /**
   * List of errors that occurred in the translation stage.
   * @type {Array<TranslationError>}
   * @memberof RecognitionMetadata
   */
  translation_errors?: Array<TranslationError>;
  /**
   * List of errors that occurred in the summarization stage.
   * @type {Array<SummarizationError>}
   * @memberof RecognitionMetadata
   */
  summarization_errors?: Array<SummarizationError>;
  /**
   * List of errors that occurred in the sentiment analysis stage.
   * @type {Array<SentimentAnalysisError>}
   * @memberof RecognitionMetadata
   */
  sentiment_analysis_errors?: Array<SentimentAnalysisError>;
  /**
   * List of errors that occurred in the topic detection stage.
   * @type {Array<TopicDetectionError>}
   * @memberof RecognitionMetadata
   */
  topic_detection_errors?: Array<TopicDetectionError>;
  /**
   * List of errors that occurred in the auto chapters stage.
   * @type {Array<AutoChaptersResultError>}
   * @memberof RecognitionMetadata
   */
  auto_chapters_errors?: Array<AutoChaptersResultError>;
  /**
   *
   * @type {AlignmentConfig}
   * @memberof RecognitionMetadata
   */
  alignment_config?: AlignmentConfig;
  /**
   *
   * @type {OutputConfig}
   * @memberof RecognitionMetadata
   */
  output_config?: OutputConfig;
  /**
   *
   * @type {LanguagePackInfo}
   * @memberof RecognitionMetadata
   */
  language_pack_info?: LanguagePackInfo;
  /**
   *
   * @type {LanguageIdentificationResult}
   * @memberof RecognitionMetadata
   */
  language_identification?: LanguageIdentificationResult;
}
