/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RecognitionDisplay } from './recognition-display';

/**
 * List of possible job output item values, ordered by likelihood.
 * @export
 * @interface RecognitionAlternative
 */
export interface RecognitionAlternative {
  /**
   *
   * @type {string}
   * @memberof RecognitionAlternative
   */
  content: string;
  /**
   *
   * @type {number}
   * @memberof RecognitionAlternative
   */
  confidence: number;
  /**
   *
   * @type {string}
   * @memberof RecognitionAlternative
   */
  language: string;
  /**
   *
   * @type {RecognitionDisplay}
   * @memberof RecognitionAlternative
   */
  display?: RecognitionDisplay;
  /**
   *
   * @type {string}
   * @memberof RecognitionAlternative
   */
  speaker?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof RecognitionAlternative
   */
  tags?: Array<string>;
}
