/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AudioEventItem } from './audio-event-item';
// May contain unused imports in some cases
// @ts-ignore
import type { Chapter } from './chapter';
// May contain unused imports in some cases
// @ts-ignore
import type { JobInfo } from './job-info';
// May contain unused imports in some cases
// @ts-ignore
import type { RecognitionMetadata } from './recognition-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { RecognitionResult } from './recognition-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RetrieveTranscriptResponseAudioEventSummary } from './retrieve-transcript-response-audio-event-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { SentimentAnalysisResult } from './sentiment-analysis-result';
// May contain unused imports in some cases
// @ts-ignore
import type { SummarizationResult } from './summarization-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TopicDetectionResult } from './topic-detection-result';
// May contain unused imports in some cases
// @ts-ignore
import type { TranslationSentence } from './translation-sentence';

/**
 *
 * @export
 * @interface RetrieveTranscriptResponse
 */
export interface RetrieveTranscriptResponse {
  /**
   * Speechmatics JSON transcript format version number.
   * @type {string}
   * @memberof RetrieveTranscriptResponse
   */
  format: string;
  /**
   *
   * @type {JobInfo}
   * @memberof RetrieveTranscriptResponse
   */
  job: JobInfo;
  /**
   *
   * @type {RecognitionMetadata}
   * @memberof RetrieveTranscriptResponse
   */
  metadata: RecognitionMetadata;
  /**
   *
   * @type {Array<RecognitionResult>}
   * @memberof RetrieveTranscriptResponse
   */
  results: Array<RecognitionResult>;
  /**
   * Translations of the transcript into other languages. It is a map of ISO language codes to arrays of translated sentences. Configured using `translation_config`.
   * @type {{ [key: string]: Array<TranslationSentence>; }}
   * @memberof RetrieveTranscriptResponse
   */
  translations?: { [key: string]: Array<TranslationSentence> };
  /**
   *
   * @type {SummarizationResult}
   * @memberof RetrieveTranscriptResponse
   */
  summary?: SummarizationResult;
  /**
   *
   * @type {SentimentAnalysisResult}
   * @memberof RetrieveTranscriptResponse
   */
  sentiment_analysis?: SentimentAnalysisResult;
  /**
   *
   * @type {TopicDetectionResult}
   * @memberof RetrieveTranscriptResponse
   */
  topics?: TopicDetectionResult;
  /**
   * An array of objects that represent summarized chapters of the transcript
   * @type {Array<Chapter>}
   * @memberof RetrieveTranscriptResponse
   */
  chapters?: Array<Chapter>;
  /**
   * Timestamped audio events, only set if `audio_events_config` is in the config
   * @type {Array<AudioEventItem>}
   * @memberof RetrieveTranscriptResponse
   */
  audio_events?: Array<AudioEventItem>;
  /**
   *
   * @type {RetrieveTranscriptResponseAudioEventSummary}
   * @memberof RetrieveTranscriptResponse
   */
  audio_event_summary?: RetrieveTranscriptResponseAudioEventSummary;
}
