/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a segment of text and its associated sentiment.
 * @export
 * @interface SentimentSegment
 */
export interface SentimentSegment {
  /**
   * Represents the transcript of the analysed segment
   * @type {string}
   * @memberof SentimentSegment
   */
  text?: string;
  /**
   * The assigned sentiment to the segment, which can be positive, neutral or negative
   * @type {string}
   * @memberof SentimentSegment
   */
  sentiment?: string;
  /**
   * The timestamp corresponding to the beginning of the transcription segment
   * @type {number}
   * @memberof SentimentSegment
   */
  start_time?: number;
  /**
   * The timestamp corresponding to the end of the transcription segment
   * @type {number}
   * @memberof SentimentSegment
   */
  end_time?: number;
  /**
   * The speaker label for the segment, if speaker diarization is enabled
   * @type {string}
   * @memberof SentimentSegment
   */
  speaker?: string;
  /**
   * The channel label for the segment, if channel diarization is enabled
   * @type {string}
   * @memberof SentimentSegment
   */
  channel?: string;
  /**
   * A confidence score in the range of 0-1
   * @type {number}
   * @memberof SentimentSegment
   */
  confidence?: number;
}
