/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SentimentChannelSummary } from './sentiment-channel-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { SentimentSpeakerSummary } from './sentiment-speaker-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { SentimentSummaryDetail } from './sentiment-summary-detail';

/**
 * Holds overall sentiment information, as well as detailed per-speaker and per-channel sentiment data.
 * @export
 * @interface SentimentSummary
 */
export interface SentimentSummary {
  /**
   *
   * @type {SentimentSummaryDetail}
   * @memberof SentimentSummary
   */
  overall?: SentimentSummaryDetail;
  /**
   * An array of objects that represent sentiment data for a specific speaker.
   * @type {Array<SentimentSpeakerSummary>}
   * @memberof SentimentSummary
   */
  speakers?: Array<SentimentSpeakerSummary>;
  /**
   * An array of objects that represent sentiment data for a specific channel.
   * @type {Array<SentimentChannelSummary>}
   * @memberof SentimentSummary
   */
  channels?: Array<SentimentChannelSummary>;
}
