/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TrackingData
 */
export interface TrackingData {
  /**
   * The title of the job.
   * @type {string}
   * @memberof TrackingData
   */
  title?: string;
  /**
   * External system reference.
   * @type {string}
   * @memberof TrackingData
   */
  reference?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof TrackingData
   */
  tags?: Array<string>;
  /**
   * Customer-defined JSON structure.
   * @type {object}
   * @memberof TrackingData
   */
  details?: object;
}
