/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Configuration for limiting the transcription of quiet audio.
 * @export
 * @interface TranscriptionConfigAudioFilteringConfig
 */
export interface TranscriptionConfigAudioFilteringConfig {
  /**
   * Controls the lower limit of audio volume at which speech and audio events will be transcribed. If the volume limit is very low, then most sound will be passed to the speech recognition engine. Higher numbers will cut out increasing amounts of sound.
   * @type {number}
   * @memberof TranscriptionConfigAudioFilteringConfig
   */
  volume_threshold?: number;
}
