/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Control punctuation settings.
 * @export
 * @interface TranscriptionConfigPunctuationOverrides
 */
export interface TranscriptionConfigPunctuationOverrides {
  /**
   * Ranges between zero and one. Higher values will produce more punctuation. The default is 0.5.
   * @type {number}
   * @memberof TranscriptionConfigPunctuationOverrides
   */
  sensitivity?: number;
  /**
   * The punctuation marks which the client is prepared to accept in transcription output, or the special value \'all\' (the default). Unsupported marks are ignored. This value is used to guide the transcription process.
   * @type {Array<string>}
   * @memberof TranscriptionConfigPunctuationOverrides
   */
  permitted_marks?: Array<string>;
}
