/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UsageDetails } from './usage-details';

/**
 *
 * @export
 * @interface UsageResponse
 */
export interface UsageResponse {
  /**
   *
   * @type {string}
   * @memberof UsageResponse
   */
  since: string;
  /**
   *
   * @type {string}
   * @memberof UsageResponse
   */
  until: string;
  /**
   *
   * @type {Array<UsageDetails>}
   * @memberof UsageResponse
   */
  summary: Array<UsageDetails>;
  /**
   *
   * @type {Array<UsageDetails>}
   * @memberof UsageResponse
   */
  details: Array<UsageDetails>;
}
