/* tslint:disable */
/* eslint-disable */
/**
 * Speechmatics ASR REST API
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. The supported job type is transcription of audio files.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { JobMode } from './job-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { JobType } from './job-type';
// May contain unused imports in some cases
// @ts-ignore
import type { OperatingPoint } from './operating-point';

/**
 *
 * @export
 * @interface UsageDetails
 */
export interface UsageDetails {
  /**
   *
   * @type {JobMode}
   * @memberof UsageDetails
   */
  mode: JobMode;
  /**
   *
   * @type {JobType}
   * @memberof UsageDetails
   */
  type: JobType;
  /**
   *
   * @type {string}
   * @memberof UsageDetails
   */
  language?: string;
  /**
   *
   * @type {OperatingPoint}
   * @memberof UsageDetails
   */
  operating_point?: OperatingPoint;
  /**
   * Total number of billable jobs in this cycle
   * @type {number}
   * @memberof UsageDetails
   */
  count: number;
  /**
   * Total duration of billable jobs (in hours) this cycle
   * @type {number}
   * @memberof UsageDetails
   */
  duration_hrs: number;
}
