import {
  getFeatures,
  RealtimeTranscriptionProvider,
} from '@speechmatics/real-time-client-react';
import { PCMAudioRecorderProvider } from '@speechmatics/browser-audio-input-react';
import { Controls } from './Controls';
import { Status } from './Status';
import { Output } from './Output';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Speechmatics Real-time example',
  description: 'Generated by create next app',
};

export default async function Page() {
  const features = await getFeatures();
  const displayNames = new Intl.DisplayNames(['en'], { type: 'language' });
  const languages = features.realtime.transcription[0].languages.map(
    (code) => [code, displayNames.of(code) ?? code] as const,
  );

  return (
    <PCMAudioRecorderProvider workletScriptURL="/js/pcm-audio-worklet.min.js">
      <RealtimeTranscriptionProvider appId="nextjs-rt-example">
        <section>
          <h3>Real-time Example</h3>
          <section className="grid">
            <Controls languages={languages} />
            <Status />
          </section>
          <section>
            <Output />
          </section>
        </section>
      </RealtimeTranscriptionProvider>
    </PCMAudioRecorderProvider>
  );
}
