import {
  getFeatures,
  RealtimeTranscriptionProvider,
} from '@speechmatics/real-time-client-react';
import type { Metadata } from 'next';
import { Controls } from '@/components/Controls';
import { Output } from '@/components/Output';
import { Status } from '@/components/Status';
import { AudioProvider } from '@/components/AudioProvider';

export const metadata: Metadata = {
  title: 'Speechmatics Real-time example',
  description: 'Generated by create next app',
};

export default async function Page() {
  const features = await getFeatures();
  const languages = features.realtime.transcription[0].languages.map((code) => {
    return [
      code,
      features.metadata.language_pack_info[code]?.language_description,
    ] as const;
  });

  return (
    <AudioProvider>
      <RealtimeTranscriptionProvider appId="nextjs-rt-example">
        <section>
          <h3>Real-time Example</h3>
          <section className="grid">
            <Controls languages={languages} />
            <Status />
          </section>
          <section>
            <Output />
          </section>
        </section>
      </RealtimeTranscriptionProvider>
    </AudioProvider>
  );
}
