name: Check branch before merging into main
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9.15.4
      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check
        run: "pnpm lint:check && pnpm format:check"
      - name: Test
        run: pnpm -r test
        env:
          API_KEY: ${{ secrets.API_KEY }}
